name: SBTA_ENV
channels:
  - defaults

dependencies:
  - python=3.11
  - pip
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - biopython
  - openpyxl
  - tqdm
  - requests
  - beautifulsoup4
  - networkx
  - pip:
      - mdtraj
      - torch
      - torchaudio
      - torchvision
      - transformers
      - datasets
      - sentencepiece
      - scikit-learn
      - matplotlib
      - seaborn

