'''
This module provides utilities for importing and structuring hydrogen bond data generated by cpptraj.

It parses `hbond ... out <file> series` output tables, extracts residue–residue hydrogen-bond
pairs from the header, and loads the corresponding time series into adjacency-matrix
representations. These system-level matrices can then be used directly for downstream
analyses (i.e., clustering, dimensionality reduction, visualization).

Rather than functioning as a generic wrapper, the focus here is on:

* Mapping atom-level cpptraj outputs to residue-level indices.
* Constructing per-frame residue×residue H-bond matrices.
* Providing template arrays for efficient modification and integration with the broader mdsa_tools pipeline.

See Also
--------
mdsa_tools.Viz.visualize_reduction
    Plot PCA/UMAP embeddings of reduced systems.
mdsa_tools.Data_gen_hbond.create_system_representations
    Build system-level adjacency matrices from trajectories.

'''

import numpy as np
import mdtraj as md
from typing import Tuple, Dict

class cpptraj_hbond_import():
    '''Lightweight loader for cpptraj hydrogen-bond (series) output.

    Init takes the filepath to the desired data file and the associated topology.
    After construction, the header is parsed to determine residue–residue index
    pairs and the time-series data are loaded into memory.

    Parameters
    ----------
    filepath : str or pathlib.Path
        Path to a cpptraj `hbond ... out <file> series` output table.
    topology : str or pathlib.Path
        Path to a topology file readable by MDTraj (i.e., AMBER `prmtop`).

    Attributes
    ----------
    indices : list of tuple of int
        Parsed residue index pairs `(res1, res2)` (1-based, AMBER `resSeq` style)
        in the same order as data columns (excluding `#Frame`).
    data : np.ndarray of int, shape=(n_frames, n_pairs)
        Binary/indicator series where each column corresponds to a header pair
        in `indices`. Rows are frames.
    topology : mdtraj.Topology
        Loaded MDTraj topology associated with the series table.

    Returns
    -------
    None
        Object is initialized with parsed attributes.

    Examples
    --------
    >>> loader = cpptraj_hbond_import("hbonds.dat", "system.prmtop")
    >>> loader.indices[:3]
    [(12, 34), (12, 35), (25, 30)]
    >>> loader.data.shape
    (n_frames, n_pairs)

    Notes
    -----
    This class assumes a header where the first field is `#Frame` followed by
    columns named like `<prefix>_<res1>@<atom1>_<res2>@<atom2>`.

    '''

    def __init__(self,filepath,topology,res_of_interest):
        '''Initialize the loader and parse header + data.

        Parameters
        ----------
        filepath : str or pathlib.Path
        Path to the cpptraj `hbond ... out <file> series` table.
        topology : str or pathlib.Path
        Path to a topology readable by MDTraj (e.g., AMBER `prmtop`).

        Returns
        -------
        None
        '''

        self.filepath=filepath
        self.residuelevel_indices=self.extract_headers(filepath=filepath)
        self.data=np.loadtxt(filepath, skiprows=1, usecols=range(1, len(self.residuelevel_indices)+1), dtype=int)
        self.res_of_interest=res_of_interest
        self.topology = md.load_topology(topology) 
        
        if res_of_interest is not None:
            sel = self.topology.select('resSeq ' + ' '.join(map(str, sorted(res_of_interest))))
            subtop = self.topology.subset(sel)   # new Topology with only wanted residues
            self.topology = subtop               # keep using the sliced topology
        

        return
     
    def extract_headers(self,filepath=None):
        '''Parse the cpptraj hydrogen-bond header to get residue–residue pairs.

        This reads only the first line of a cpptraj `hbond ... out <file> series`
        table and extracts the residue indices for each H-bond column. It expects
        a leading `#Frame` column followed by columns named like
        `<prefix>_<res1>@<atom1>_<res2>@<atom2>` (i.e., `HB_12@N_34@O`).
        The returned pairs are 1-based residue indices (AMBER `resSeq` style),
        ordered exactly as the data columns appear in the file.

        Parameters
        ----------
        filepath : str or pathlib.Path
            Path to the cpptraj `hbond` series output file. Must contain a header
            line beginning with `#Frame` and column names formatted as described
            above.

        Returns
        -------
        indices : list of tuple of int
            A list of `(res1, res2)` residue index pairs (1-based) corresponding
            to the non-`#Frame` columns in the header, in column order. These
            indices are intended to be used later to place column values into a
            residue×residue adjacency matrix at positions `[res1-1, res2-1]`.

        Raises
        ------
        FileNotFoundError
            If `filepath` does not exist.
        ValueError
            If a header token cannot be parsed into integer residue indices.

        Notes
        -----
        * Only the first line is inspected; data lines are not parsed here.
        * Column names must contain at least three underscore-separated tokens:
          a freeform prefix, `<res1>@<atom1>`, and `<res2>@<atom2>`.

        Examples
        --------
        Suppose the header line looks like::

            #Frame HB_12@N_34@O HB_12@N_35@O HB_25@O_30@H

        Then::

            indices = obj.extract_headers("hbonds.dat")
            # indices == [(12, 34), (12, 35), (25, 30)]
        '''
        filepath = filepath if filepath is not None else self.filepath

        lines=[]
        indices=[]
        with open(filepath,'r') as infile:
            for line in infile:
                lines.append(line.split())

        for col_header in lines[0]:
            if col_header !='#Frame':
                res1 = col_header.split('_')[1].split('@')[0]
                res2 = col_header.split('_')[2].split('@')[0]
                indices.append((int(res1),int(res2)))
                
        return indices

    def edgelist_single_frame(self,topology=None,granularity=None):
        '''Create an upper‑triangle residue–residue edge template for one frame.

        Parameters
        ----------
        topology : mdtraj.Topology or str or pathlib.Path or None, optional
        Topology object or path. If ``None``, uses ``self.topology``.
        granularity : {'residue'}, optional
        Placeholder for future atom‑ or group‑level variants. Only residue‑
        level edges are constructed at the moment.

        Returns
        -------
        np.ndarray of int, shape (E, 2)
        Each row is a pair ``(i, j)`` with ``i < j`` using 0‑based MDTraj
        residue indices. The set corresponds to the upper triangle of an
        ``n_residues × n_residues`` matrix.

        Notes
        -----
        Use :meth:`lookup_table_from_edgelist` to convert ``(i, j)`` pairs to
        contiguous row indices for vectorized time‑series storage.

        '''

        topology = topology if topology is not None else self.topology

        granularity = granularity if granularity is not None else 'residue'

        #Make atom to residue dictionary 

        #Create adjacency matrix, set first row and column as residue indices, and multiply to match the number of frames
        
        row_indexes, column_indexes = np.triu_indices(topology.n_residues, k=1)

        # 1-based residue labels (since your original indexing is 1..N)
        edge_table = np.column_stack([row_indexes, column_indexes])   # shape (E, 3)
        
        return edge_table
    
    def lookup_table_from_edgelist(self,edge_list_template=None):
        '''Build a fast ``(i, j) → row`` lookup for the edge template.

        Parameters
        ----------
        edge_list_template : np.ndarray of int or None, shape (E, 2)
        Output of :meth:`edgelist_single_frame`. If ``None``, a template is
        generated from the current topology.

        Returns
        -------
        np.ndarray of int, shape (n_residues, n_residues)
        Dense table ``pair2row`` where ``pair2row[i, j]`` gives the row index
        into the edge list for pair ``(i, j)`` (0‑based). Symmetric with
        diagonal set to ``-1`` as a sentinel for "no mapping".
        '''

        edge_list_template=edge_list_template if edge_list_template is not None else self.edgelist_single_frame()
        #print(edge_list_template.shape)
        #print(edge_list_template)
        #grab residue indexes as int bc we need int
        res1 = edge_list_template[:, 0].astype(np.int32)
        res2 = edge_list_template[:, 1].astype(np.int32)
        idx = np.arange(res1.size)

        #we can now initiate a table of empty -1s and then fill in the row index for pairwise comparisons so we can easily grab row indexes for comparisons
        #it really does not mean much we used -1, just decent convention for missing value, NAN, zeroes etc would be the same but since we are dealing
        #with indexes -1 is a nice simple flag for grabbing things
        pair2row = -np.ones((self.topology.n_residues+1, self.topology.n_residues+1), dtype=np.int32)
        pair2row[0,0]=0
        #print(self.res_of_interest)
        pair2row[0,1:]=self.res_of_interest
        pair2row[1:,0]=self.res_of_interest

        #pulling out just data
        subset=pair2row[1:,1:]
        subset[res1, res2] = idx
        subset[res2, res1] = idx  # undirected

        #adding it back in
        pair2row[1:,1:]=subset

        
        return pair2row

    def iterate_frames(self,data=None,headers=None):
        '''Map each frame's series values onto an edge‑vector scaffold.

        Parameters
        ----------
        data : np.ndarray or None, shape (n_frames, n_pairs)
        Integer/binary cpptraj series. Defaults to ``self.data``.
        headers : list[tuple[int, int]] or None
        Header residue pairs `(res1, res2)` (1‑based). Defaults to
        ``self.residuelevel_indices``.

        Returns
        -------
        None


        Notes
        -----
   
        '''

        data=data if data is not None else self.data
        headers=headers if headers is not None else self.residuelevel_indices
        
        lookuptable = self.lookup_table_from_edgelist()
        edge_list_size = int((lookuptable[1:,1:].shape[0]*(lookuptable[1:,1:].shape[0]-1))/2)


        all_edge_lists = []
        labels = lookuptable[0, :]       # resSeq 
        lab2pos = {lab: i for i, lab in enumerate(labels)}  # make dictionary matching index to label
        

        #iterate through lines of whatever table is loaded
        for linenumber in range(data.shape[0]):
            
            current_values=data[linenumber,:]
            frame_edgelist=np.zeros(edge_list_size,dtype=int)

            for i in range(current_values.shape[0]):
                current_comparison = headers[i]

                

                y_cord=lab2pos[current_comparison[0]]
                x_cord=lab2pos[current_comparison[1]]
                
          

                current_index = lookuptable[x_cord, y_cord]
                
                current_value = current_values[i]

                if current_value>0:
                    frame_edgelist[current_index]+=current_value
            
            all_edge_lists.append(frame_edgelist)
            
        all_edge_lists = np.vstack(all_edge_lists)
       
        return all_edge_lists
          

if __name__ == '__main__':

    from mdsa_tools.Data_gen_hbond import TrajectoryProcessor as tp
    import numpy as np
    import os

    topology = '../PDBs/5JUP_N2_GCU_nowat.prmtop'
    traj = '../PDBs/Break_On_Fake_Cpptraj_Data.dat' 



    # a) By 0-based residue index (MDTraj's "resid")
    #residues=['resid 12 13 14 15 22 23 24 25 26 27 28 29 30 45 46 47 48 49 50 64 65 66 67 68 69 70 71 72 74 75 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 163 164 165 166 167 168 169 170 171 172 173 174 183 184 185 186 187 188 189 190 191 192 193 194 196 197 221 222 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 255 256 257 258 259']
    #residues=[13,14,15,16,23,24,25,26,27,28,29,30,31,46,47,48,49,50,51,65,66,67,68,69,70,71,72,73,75,76,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,164,165,166,167,168,169,170,171,172,173,174,175,184,185,186,187,188,189,190,191,192,193,194,195,197,198,222,223,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,256,257,258,259,260,261,262,263,264,265,266,267,268,269,288,289,320,321,322,323,324,325,326,327,328,329,330,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,420,421,422,423,424,425,426,427,428,429,430,444,445,446,447,448,449,450,451,452,461,462,463,464,465,466,467,468,480,481,482,483,484,485,486,487,488,489]
    residues = [95,230,232,234,235,236,237,238,239,240,241,242,243,244,245,246]
    test_trajectory = cpptraj_hbond_import(filepath=traj,topology=topology,res_of_interest=residues)

    feature_matrix=test_trajectory.iterate_frames()
    print(feature_matrix)
    print(feature_matrix.shape)
    
    from mdsa_tools.Analysis import systems_analysis

    Analyzer=systems_analysis(precomputed_feature_matrix=feature_matrix,res_indexes_for_precomputedmatrix=residues)

